### PR TITLE
An endpoint to return status 200 if everything is OK, status 417 otherwise

### PR DESCRIPTION
**Pull request by kohsuke**
Massaged version of PR #7.

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees

**Comment by jglick** [comment]
> **417 Expectation Failed**
> The server cannot meet the requirements of the `Expect` request-header field.

Does not sound appropriate. The whole 4xx series is for client errors, which this presumably is not. I would suggest 503 Service Unavailable.

**Comment by kohsuke** [comment]
:+1:

**Comment by jglick** [comment]
I do not think you can :+1: a PR you file yourself!

**Comment by kohsuke** [comment]
This is Daya's PR!

**Comment by stephenc** [comment]
:+1:

**Comment by stephenc** [comment]
@kohsuke if you need a release feel free to roll one (I'm off the clock and wearing my OSS plugin maintainer hat)

**Comment by daniel-beck** [comment]
> 503 Service Unavailable

Sent by reverse proxies, so could be mistaken for that. But I guess in that case it doesn't matter exactly in which way Jenkins is broken?

**Pull request merged**
