### PR TITLE
bump bom

### PR DESCRIPTION
**Pull request by jetersen**
reincremental and pct ready

since CD is enabled I made it so for this branch. So hopefully when ready to release. Simply execute the cd workflow on this branch!

https://github.com/jenkinsci/bom/pull/1275

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jetersen** [comment]
Cofirmed working in `bom` `2.319.x` line

**Comment by timja** [comment]
@alecharp possible to take a look?

**Comment by alecharp** [comment]
@jetersen so, if I understand correctly, this is so we keep 2 versions of metrics? One based on `4.1.6` and another one on `4.2.x`?

**Comment by jetersen** [comment]
This is a backport which is needed for older line of Jenkins version. Since you bumped jenkins versions in recent PRs.

This backport is a fix to the `4.1.6.1-x` branch

**Comment by jetersen** [comment]
Looking at it this could potentially also target [4.1.6.2](https://github.com/jenkinsci/metrics-plugin/releases/tag/metrics-4.1.6.2)

**Comment by jetersen** [comment]
> One based on 4.1.6 and another one on 4.2.x?

No, this is so we can keep `4.1.6.1-x`. a metrics revision `4.2.x` does not exist. however a `4.1.10` does. See #177

**Comment by jetersen** [comment]
Basically I need this for an older jenkins version as we try to keep dependency management in check over here:
https://github.com/jenkinsci/bom/blob/9076c8f94d496e10bf2bfe1c3f90023087a5f781/bom-2.319.x/pom.xml#L75-L79

And this needs to be pinned because `4.1.6.1` uses jenkins.version `2.319.1` where `4.1.6.2` uses `2.332.1`

We can release this, using the cd workflow and pointing at this branch.

This should have a label that would trigger a release.

**Review by alecharp — APPROVED** [review]

**Comment by jetersen** [comment]
@alecharp if you put a `developer` label on and go here: https://github.com/jenkinsci/metrics-plugin/actions/workflows/cd.yml and run the workflow manually on `4.1.6.1-x` it should trigger a release 😄

**Comment by alecharp** [comment]
Thanks I was looking for that!

**Comment by alecharp** [comment]
`4.1.6.1-x` is missing a `workflow-dispatch`. Looking into this.

**Comment by jetersen** [comment]
again the reason we started using developer in plugins. There are inter dependencies and those only matter to developers. So in essence it makes sense.

**Comment by jetersen** [comment]
Oh it needs the workflow. Okay should be easy to push the fix to it :)

**Comment by alecharp** [comment]
`cd` workflow was not imported in `4.1.6.1-x` branch. Cherry picking it now.

**Comment by alecharp** [comment]
it didn't trigger the release.

**Comment by jetersen** [comment]
Try triggering it manually. I don't see a workflow dispatch for `4.1.6.1-x` branch

**Comment by jetersen** [comment]
Last manual run had CI failed: https://github.com/jenkinsci/metrics-plugin/runs/7516840247?check_suite_focus=true properly because you pushed a commit too soon. It tries to verify jenkins status as well.

**Comment by alecharp** [comment]
hey, I did that but too early. It's going fine now. Sorry for all this delay.

**Comment by jetersen** [comment]
@alecharp no worries. All good :)

**Comment by jetersen** [comment]
Sweet 👏

**Review by alecharp — APPROVED** [review]

**Pull request merged**
