### PR TITLE
JENKINS-69817 Changing the condition for subtask

### PR DESCRIPTION
**Pull request by sundergopalsingh**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by sundergopalsingh** [comment]
Added the condition for sub task checking similar to what was available before the regression. 
Refer:- https://github.com/jenkinsci/metrics-plugin/commit/3e254ce1d19007893a15cd97e42a5f7f1e8e40d4#diff-37b55b8fb26f49495e7308226e845ea17c4770ac15c4af8d9a14dbdab1b8e557L918 #190

**Comment by jglick** [comment]
https://issues.jenkins.io/browse/JENKINS-69817 amending #127. Seems plausible. Without test coverage one can only guess. I am not a maintainer.

**Comment by sundergopalsingh** [comment]
@alecharp Can you review this change?

**Comment by sundergopalsingh** [comment]
@alecharp Did you get a chance to review this code?

**Comment by Dohbedoh** [comment]
ping @jenkinsci/metrics-plugin-developers

**Comment by alecharp** [comment]
I don't know if the `!=` is enough / great to see if the current task is a subtask or not. 
@sundergopalsingh have you try this implementation on a working instance? is it providing the output you were expecting?

As Jesse said, without tests it hard to be sure about this addition.

**Comment by alecharp** [comment]
Closing in favor of #204.

**Pull request closed without merging**
