### PR TITLE
Use `ExecutorListener` to avoid excessive thread creation

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-66506](https://issues.jenkins.io/browse/JENKINS-66506)

Downstream of https://github.com/jenkinsci/jenkins/pull/5841. Subsumes #126.

Careful code review would certainly be appreciated, esp. by @stephenc since the precise meaning of these different timing numbers was difficult to infer.

### CODE REVIEW

**Comment by jglick** [comment]
ping @alecharp

**Review by alecharp — DISMISSED** [review]
This is very nice! Thank you @jglick

**Review by raul-arabaolaza — DISMISSED** [review]
The right core version has been released, everything looks good to me

**Comment by jglick** [comment]
Remember to check the simpler and safer #126 first. Diff of this PR will be complicated somewhere by including that one.

**Review by alecharp — APPROVED** [review]

**Comment by jglick** [comment]
Should have been labeled `'bug` prior to merge to get proper Release Drafter categorization

**Comment by alecharp** [comment]
yes, it should have. I edited the release manually. In the end, release drafter is just helping to get the release note complete.

**Comment by jglick** [comment]
https://github.com/jenkins-infra/interesting-category-action/issues/1 BTW

**Pull request merged**
