### PR TITLE
[JENKINS-31054] Generate button does not work

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-31054](https://issues.jenkins-ci.org/browse/JENKINS-31054)

@reviewbybees, specially @stephenc

### CODE REVIEW

**Comment by recena** [comment]
I've done tests using Firefox and Chrome on Ubuntu. It would be nice to try it using IE.

**Comment by stephenc** [comment]
@recena I believe it was `window.event` to make it work on IE (but that is hazy recollection at best)

**Comment by recena** [comment]
@stephenc I'm working to try it using IE. I have several VMs to do this kind of tests.

**Comment by recena** [comment]
@stephenc I did a test using IE10 on Windows 7.

jenkins-31054

**Comment by stephenc** [comment]
@recena probably was IE6 or 7 or 8 at the time... :bee:

**Comment by stephenc** [comment]
Oooh I assume you tried Safari as well ;-)

**Comment by recena** [comment]
@stephenc I'm following [this](https://wiki.jenkins-ci.org/display/JENKINS/Browser+Compatibility+Matrix) guideline. Using Safari Versión 9.0 (9537.86.1.56.2) works fine.

**Comment by oleg-nenashev** [comment]
:bee: since it has been tested

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
