### PR TITLE
Allow programmatic configuration of access keys

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This allows you to configure access keys for the metrics API in system groovy code.

### CODE REVIEW

**Comment by stephenc** [comment]
So why do you need this? If you want to inject programmatic access keys, you implement the `MetricsAccessKey.Provider` API and just provide the ones you want.

The access keys in DescriptorImpl are expressly for user configuration

**Comment by rickard-von-essen** [comment]
True, but it's way simpler use it with a public constructor and there isn't any reason to restrict this.

**Comment by stephenc** [comment]
The design was explicitly this way to separate the ones managed programmatically from the ones managed by the user.

And in any case 

```
@Extension
public class MyOnes extends Provider {
...
}
``` 

is hardly onerous

**Comment by stephenc** [comment]
> there isn't any reason to restrict this

If the tokens are being created programmatically then the user has no way to track what was issued.

Hence this is explicitly UI based.

**Pull request closed without merging**
