### PR TITLE
Upgrade the version of metrics to 3.1.2

### PR DESCRIPTION
**Pull request by stephenc**
involves a group id change but the package names are the same.

Also fix a bug caught by findbugs

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
:bee:

**Comment by varmenise** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by jtnord** [comment]
:bee:

**Comment by stephenc** [comment]
merging as maintainer

**Pull request merged**
