### PR TITLE
Replace png icon with vector graphic

### PR DESCRIPTION
**Pull request by NotMyFault**
A simple pr that aims to replace the clock png with a svg. https://issues.jenkins.io/browse/JENKINS-66704

Before:

After:

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
Any news on this on blocking a merge? 

(cc @alecharp I guess?)

**Comment by alecharp** [comment]
@NotMyFault looks ok. But did you test and all the web browsers supported: https://www.jenkins.io/doc/administration/requirements/web-browsers/? Thanks.

**Comment by NotMyFault** [comment]
> @NotMyFault looks ok. But did you test and all the web browsers supported: https://www.jenkins.io/doc/administration/requirements/web-browsers/? Thanks.

Yeah, it works out nicely. Just gave it an additional test on Edge and Firefox, as I don't use them as frequent as I use others.

**Comment by alecharp** [comment]
Same for Internet explorer 11? Sorry, I don't have this web browser to test on my own.

**Comment by NotMyFault** [comment]
No worries, I quickly gave it a test on my surface and it looks good. Though it appears it's superseded by Edge or whatever the default is nowadays.

**Comment by NotMyFault** [comment]
@alecharp 👀

**Comment by alecharp** [comment]
Sorry yes, this looks good. I'll spin the plugin quickly on my machine and will merge this is no problem

**Comment by alecharp** [comment]
Looks good and complete. Thank you for the contribution.

**Pull request merged**
